
language: node_js
# sudo: required
addons:
  chrome: stable
node_js:
  - 14
os: linux

jobs:
  include:
    - stage: eslint check
      script: npm run eslint
    - stage: stylelint check
      script: npm run stylelint
    - stage: unit test
      script: npm run test
