
language: node_js
# sudo: required
addons:
    chrome: stable
node_js:
- 14
os: linux
cache:
  yarn: true
branches:
  only:
  - master
  - dev
install:
- |
    yarn
script:
- |
    yarn run eslint && yarn run stylelint && yarn run test
after_success:
- |
    cat ./test/coverage/lcov.info | ./node_modules/.bin/codecov
