
language: node_js
# sudo: required
addons:
    chrome: stable
node_js:
- 14
os: linux
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
branches:
  only:
  - master
  - dev

jobs:
  include:
    - stage: eslint check
      script: npm run eslint
    - stage: stylelint check
      script: npm run stylelint
    - stage: unit test
      script: npm run test
